---
# tasks file for kubectl | EL Family

- name: EL Family | Downloading archive for {{ kubectl_app }} {{ kubectl_version }} to {{ kubectl_bin_path }}
  ansible.builtin.get_url:
    url: "{{ kubectl_dl_url }}"
    dest: "{{ kubectl_bin_path }}/{{ kubectl_app }}"
    mode: "{{ kubectl_file_mode }}"
